services:
  mongodb:
    image: mongo:6
    ports: ["27017:27017"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports: ["3000:3000"]
    env_file: api-gateway/.env
    depends_on: [auth, user, product, order, redis]

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file: services/auth/.env
    depends_on: [mongodb, redis]

  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    env_file: services/user/.env
    depends_on: [mongodb]

  product:
    build:
      context: .
      dockerfile: services/product/Dockerfile
    env_file: services/product/.env
    depends_on: [mongodb]

  order:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    env_file: services/order/.env
    depends_on: [mongodb, rabbitmq]

  payment:
    build:
      context: .
      dockerfile: services/payment/Dockerfile
    env_file: services/payment/.env
    depends_on: [rabbitmq]

  inventory:
    build:
      context: .
      dockerfile: services/inventory/Dockerfile
    env_file: services/inventory/.env
    depends_on: [mongodb, rabbitmq]
